# Required by pipeline
check_for_builtin_functions:
  comment: ''

check_for_generic_operating_system_services:
  comment: ''

check_for_plain_text_credentials_in_python:
  comment: ''

check_for_insecure_http_calls_in_python:
  comment: ''

check_for_secret_disclosure:
  comment: ''

check_for_executable_flag:
  comment: ''